gazebo_ros_control:
  pid_gains:
    shoulder_pan_joint:
      p: 100
      i: 1 
      d: 10
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    shoulder_lift_joint:
      p: 100
      i: 1
      d: 10
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    elbow_joint:
      p: 100
      i: 1
      d: 10
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    wrist_1_joint:
      p: 100
      i: 1
      d: 10
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    wrist_2_joint:
      p: 100
      i: 1
      d: 10
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    wrist_3_joint:
      p: 100
      i: 1
      d: 10
      i_clamp: 0.2
      antiwindup: false
      publish_state: true


